application:
  port: 8080
database:
  port: 5431
  host: 'localhost'
  username: 'postgres'
  password: 'postgres'
  database_name: 'zerodb'
  timeout_milliseconds: 2000
email_client:
  base_url: 'localhost'
  sender_email: 'test@gmail.com'
  authorization_token: 'my-secret-token'
  timeout_milliseconds: 1000
