application:
  host: 0.0.0.0
database:
  require_ssl: true
  tmeout_milliseconds: 4000
email_client:
  base_url: 'https://api.postmarkapp.com'
  sender_email: 'system@domanic.io'
  timeout_milliseconds: 10000
